### ISSUE TITLE
Build errors with later distributions

### ISSUE THREAD

**Issue by chrhansk** [felixlen/trlib#14]
The build fails on later distributions (Debian Bullseye and Ubuntu Bionic):

    Scanning dependencies of target trlib
    [  1%] Building C object src/CMakeFiles/trlib.dir/trlib_krylov.c.o
    [  2%] Building C object src/CMakeFiles/trlib.dir/trlib_tri_factor.c.o
    [  2%] Building C object src/CMakeFiles/trlib.dir/trlib_leftmost.c.o
    [  3%] Building C object src/CMakeFiles/trlib.dir/trlib_eigen_inverse.c.o
    [  4%] Building C object src/CMakeFiles/trlib.dir/trlib_quadratic_zero.c.o
    [  5%] Linking C shared library libtrlib.so
    [  5%] Built target trlib
    [  6%] Generating test_factor_tri_simple_indef_valgrind.c
    Scanning dependencies of target test_factor_tri_simple_indef_valgrind
    [  7%] Building C object tests/CMakeFiles/test_factor_tri_simple_indef_valgrind.dir/test_factor_tri_simple_indef_valgrind.c.o
    [  8%] Building C object tests/CMakeFiles/test_factor_tri_simple_indef_valgrind.dir/trlib_test.c.o
    [  8%] Linking C executable test_factor_tri_simple_indef_valgrind
    /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcheck.a(check.o): In function `check_get_clockid':
    (.text+0xab3): undefined reference to `timer_create'
    (.text+0xad5): undefined reference to `timer_delete'
    /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcheck.a(check_run.o): In function `srunner_run':
    (.text+0xa92): undefined reference to `timer_create'
    (.text+0xae0): undefined reference to `timer_settime'
    (.text+0xb0a): undefined reference to `timer_delete'
    /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcheck.a(check_log.o): In function `subunit_lfun':
    (.text+0x5f4): undefined reference to `subunit_test_start'
    (.text+0x6bf): undefined reference to `subunit_test_fail'
    (.text+0x6d4): undefined reference to `subunit_test_pass'
    (.text+0x6ef): undefined reference to `subunit_test_error'
    collect2: error: ld returned 1 exit status
    tests/CMakeFiles/test_factor_tri_simple_indef_valgrind.dir/build.make:129: recipe for target 'tests/test_factor_tri_simple_indef_valgrind' failed

Specifically, there seems to some linker error regarding libcheck. Could you look into the problem and maybe also update the travis file to include a build matrix containing some more recent Ubuntu distros like Focal and Bionic? Those should be [supported](https://docs.travis-ci.com/user/reference/overview/) ?!

**Comment by felixlen** [comment]
Thanks for pointing that out. It seems to be the issue described here: https://github.com/gnuradio/gnuradio/issues/3581, I have worked around the CMakeModules file by moving the include for PkgConfig. Will look into the build matrix later.

**Comment by chrhansk** [comment]
I noticed that

    Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on. 

The last build is 10 months old, maybe you need to adjust your CI settings?!

**Comment by felixlen** [comment]
Yes, I also noticed this. At the moment I am in the process of moving to GitHub actions.

**Comment by felixlen** [comment]
Travis has been migrated to Github Actions, for the moment only testing on the latest Ubuntu LTS version.
