### ISSUE TITLE
Add a release/tag

### ISSUE THREAD

**Issue by traversaro** [felixlen/trlib#22]
Hello @felixlen, thanks a lot for working on trlib ! 

I am interested in adding trlib as package in [conda-forge](https://conda-forge.org/) to simplify its installation (and also because it is a dependency of https://github.com/chrhansk/sleqp that I am also interested in packaging). For doing that, it would be useful to add git tags to indicate the point of the history that refer to a precise version. For example, I see that you are keeping a version number in CMake (see https://github.com/felixlen/trlib/commit/0998af9d63ced573446dfba15881269583a8f41b), would you be interested in adding a tag to indicate which git commit in history is the trlib version 0.4?

Thanks a lot in advance, and if you are not interested in adding tags to the repo, no problem!

**Comment by felixlen** [comment]
Hello @traversaro,

thanks for the suggestion. I have done so for the current status, but will not add tags for previous versions.

Let me know if it works for you with the tag I created or you need something else?

**Comment by traversaro** [comment]
That is perfect, thanks! Yes, it is perfectly fine for me just to have the latest tag.
