### ISSUE TITLE
Python2 installation

### ISSUE THREAD

**Issue by rgiordan** [felixlen/trlib#3]
I'm interested in trying out trlib, but I can't get it to work with python2.  In ```CMakeLists.txt``` I set ```option(TRLIB_BUILD_PYTHON2 ON)``` and ran ```make```, ```make doc```, ```make test```, and ```make install```.  Even running python in the cmake ```build``` directory, though, I cannot ```import trlib``` (it says module not found).  I see that a ```./bindings/python/trlib.pyx``` file was generated, but no ```py``` files.  A simple ```pyximport``` also failed.  Any ideas?

**Comment by felixlen** [comment]
Hi Ryan,
thanks for your feedback. If the python interface compilation works, there should be `trlib.so` in the `build` directory (assuming you are running linux). What you describe sounds right, so a couple of questions to locate the failure:

- Which platform are you using? Linux?
- Can you confirm that in `build/CMakeCache.txt` the variable `TRLIB_BUILD_PYTHON2` is turned `ON` as well? For me this looks like:

    ```
    >>> cat CMakeCache.txt | grep PYTHON2 
    TRLIB_BUILD_PYTHON2:BOOL=ON
    //MODIFIED property for variable: TRLIB_BUILD_PYTHON2
    TRLIB_BUILD_PYTHON2-MODIFIED:INTERNAL=ON
    ```

- Can you post the output of `make clean && make`?

Thanks,
Felix

**Comment by rgiordan** [comment]
Sorry to be slow, I was out of town.  Thanks for responding!

- I'm running Ubuntu 16.04.
- Actually, in ```build/CMakeCache.txt```, I see ```TRLIB_BUILD_PYTHON2:BOOL=OFF```.  I still see this after deleting ```build``` and re-running ```cmake```, even though it is on in the ```CMakeLists```:
```
$ cat ../CMakeLists.txt | grep PYTHON2
option(TRLIB_BUILD_PYTHON2 ON)
```

Presumably, given this, ```make clean && make``` won't be useful.

**Comment by rgiordan** [comment]
Strangely, the comment in ```CMakeCache.txt``` says ```ON```:

```
//ON
TRLIB_BUILD_PYTHON2:BOOL=OFF
```

I am relatively new to ```cmake```; maybe I'm just doing something silly here.

**Comment by rgiordan** [comment]
Ok, after a little googling I tried this:

```
cmake -DTRLIB_BUILD_PYTHON2=ON ..
```

After ```make``` and ```make install```, it now works.  For newbies like me it might be worth making a note in the installation instructions.  Thanks for pointing me in the right direction!

**Comment by felixlen** [comment]
Dear Ryan,

thanks for your feedback. Exactly, you can either pass options to cmake on the commandline with `-D` as you found out. The other option is to install `ccmake` that provides you a nice interface to set those options.

You can install it Ubuntu via

    sudo apt install ccmake

and then invoke it when you are in build folder by calling

    ccmake .

Now you can toggle options just by selecting them, pressing `Enter` to toggle and `c` after that to rerun the configure scripts. You quit `ccmake` by pressing `e` and can then continue with the usual `make` etc toolchain.
