### ISSUE TITLE
C linking errors

### ISSUE THREAD

**Issue by yao-yl** [felixlen/trlib#4]
Hi,
I was trying to install _trilb_ library but I didn't succeed. I am running C interface on Mac OS 10.12.6. I followed all steps in the documentation.   It looks fine when I set up `cmake` with all default settings and run `make`:
```
Scanning dependencies of target trlib
[ 16%] Building C object src/CMakeFiles/trlib.dir/trlib_krylov.c.o
[ 33%] Building C object src/CMakeFiles/trlib.dir/trlib_tri_factor.c.o
[ 50%] Building C object src/CMakeFiles/trlib.dir/trlib_leftmost.c.o
[ 66%] Building C object src/CMakeFiles/trlib.dir/trlib_eigen_inverse.c.o
[ 83%] Building C object src/CMakeFiles/trlib.dir/trlib_quadratic_zero.c.o
[100%] Linking C shared library libtrlib.dylib
[100%] Built target trlib

```

 When I compile the file using` make test`, it returns 
```
Running tests...
Test project /Users/YulingYao/desktop/trlib-master/build
No tests were found!!!
```
OK, I guess this just doesn't matter. 
It also looks fine  when I execute ` make install` and `sudo make install.`

```
[100%] Built target trlib
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/include/trlib.h
-- Up-to-date: /usr/local/include/trlib/trlib_types.h
-- Up-to-date: /usr/local/include/trlib/trlib_krylov.h
-- Up-to-date: /usr/local/include/trlib/trlib_tri_factor.h
-- Up-to-date: /usr/local/include/trlib/trlib_leftmost.h
-- Up-to-date: /usr/local/include/trlib/trlib_quadratic_zero.h
-- Up-to-date: /usr/local/include/trlib/trlib_eigen_inverse.h
......
-- Installing: /usr/local/lib/libtrlib.dylib
......
```

It should work. However, I still end up with a linking error whenever I call the library in C
`LDLIBS = -ltrlib  ...`
```
ld: library not found for -ltrlib
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

I guess I just didn't install the whole package successfully. When I manually link the binary with library in Xcode, I also didn't find any trilb framework. (I suppose the library itself should be generated in the CMAKE_OSX_SYSROOT path according to the CMake file, but it wan't.) 

I googled for a while and find nothing directly related.  Could you provide any suggestion? 

Thanks,
Yuling

**Comment by apotschka** [comment]
Have you tried 
`LDLIBS = -L/usr/local/lib -ltrlib ...`
in order to provide the location of the library to the linker?

For running the executable later, you might have to set `DYLD_LIBRARYPATH=/usr/local/lib/`.

As a side remark: `/usr/local` is not a standard OSX path like in Linux. `Macports` for instance installs to `/opt`.

Cheers, Andreas

**Comment by felixlen** [comment]
Regarding the tests: Did you install the Check library? Otherwise no tests are compiling.

**Comment by yao-yl** [comment]
Thanks for the reply. I installed Check library just now, and then everything broke down...  After I run `make`, it returns 
```
dyn-160-39-144-205: $ make
[  1%] Building C object src/CMakeFiles/trlib.dir/trlib_krylov.c.o
[  2%] Building C object src/CMakeFiles/trlib.dir/trlib_tri_factor.c.o
[  2%] Building C object src/CMakeFiles/trlib.dir/trlib_leftmost.c.o
[  3%] Building C object src/CMakeFiles/trlib.dir/trlib_eigen_inverse.c.o
[  4%] Building C object src/CMakeFiles/trlib.dir/trlib_quadratic_zero.c.o
[  5%] Linking C shared library libtrlib.dylib
[  5%] Built target trlib
[  6%] Generating test_krylov_zero_hessian_valgrind.c
sed: 1: "/sr\ =\ srunner_create( ...": extra characters after \ at the end of a command
make[2]: *** [tests/test_krylov_zero_hessian_valgrind.c] Error 1
make[2]: *** Deleting file `tests/test_krylov_zero_hessian_valgrind.c'
make[1]: *** [tests/CMakeFiles/test_krylov_zero_hessian_valgrind.dir/all] Error 2
make: *** [all] Error 2
```
I believe this part was skipped when I didn't have Check library. But I become more confusing now...

**Comment by felixlen** [comment]
Dear Yao,

I removed that part if the platform is Mac OS as valgrind is not available to this platform anyways. Could you test again after updating git?

Best,
Felix

**Comment by yao-yl** [comment]
Hi Felix,
I run into some linking error again when I run `make`,
```
dyn-160-39-144-205:build YulingYao$ make
[  1%] Building C object src/CMakeFiles/trlib.dir/trlib_krylov.c.o
[  3%] Building C object src/CMakeFiles/trlib.dir/trlib_tri_factor.c.o
[  5%] Building C object src/CMakeFiles/trlib.dir/trlib_leftmost.c.o
[  6%] Building C object src/CMakeFiles/trlib.dir/trlib_eigen_inverse.c.o
[  8%] Building C object src/CMakeFiles/trlib.dir/trlib_quadratic_zero.c.o
[ 10%] Linking C shared library libtrlib.dylib
[ 10%] Built target trlib
[ 11%] Building C object tests/CMakeFiles/test_krylov_3d_all_cases.dir/test_krylov_3d_all_cases.c.o
[ 13%] Building C object tests/CMakeFiles/test_krylov_3d_all_cases.dir/trlib_test.c.o
[ 15%] Linking C executable test_krylov_3d_all_cases
ld: library not found for -lcheck
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tests/test_krylov_3d_all_cases] Error 1
make[1]: *** [tests/CMakeFiles/test_krylov_3d_all_cases.dir/all] Error 2
make: *** [all] Error 2
 
```
I do have `check` library installed. It sounds weird to me because if check is not found, all the testing part will not be executed. 
It is always painful to make platform transfer. Thank you so much for your patience. 
Yuling

**Comment by felixlen** [comment]
`check` is found using CMakes `find_package(Check)` and compilation of the tests executed if `CHECK_FOUND` is set to true. Linking is then done again `${CHECK_LIBRARIES}`, provided by the `CMake` script. I suspect that this is exactly the same problem as you are having in the initial post. I am a bit unsure how to best proceed here, as I don't know about the internals of your installation.

**Comment by yao-yl** [comment]
Hi,
I am still not sure what is going wrong so I reinstalled everything. Surprising it works this time.... Thank you for your comments!
Yuling

**Comment by felixlen** [comment]
@yao-yl Thanks, good to know! Best,Felix
