### ISSUE TITLE
Issues if gradient and Hessian contain only zeros

### ISSUE THREAD

**Issue by jomi2801** [felixlen/trlib#5]
I have experience some issues with trlib. If I run trlib with zero gradient and Hessian, the result is a NaN vector. Here some code:
```
julia> include("/home/johannes/trlib/bindings/julia/trlib.jl")
julia> using trlib
julia> H = zeros(3, 3); g = zeros(3); radius = 1.0; 
julia> TR = trlib.trlib_data(H, g);
julia> trlib.trlib_solve(TR, 1.0);
julia> TR.sol
3-element Array{Float64,1}:
 NaN
 NaN
 NaN
```

**Comment by felixlen** [comment]
Please note that the method is iterative and thus searches solutions in the Krylov subspace generated from the hessian and gradient consisting of powers of the hessian applied to the gradient. That subspace is zero in the case of zero hessian and gradient and your trivial example is not any meaningful input for the algorithm. I will add a test to handle this very special case.

**Comment by jomi2801** [comment]
Thanks for the information. I just came across that problem since I am running multiple trust-region problems and one happened to be a "zero problem." I agree it is not meaningful however I think that the code should be able to handle that case...

**Comment by felixlen** [comment]
For sure. I will add a test for this.

Just wanted to explain why this happens and why this case is unusual.

**Comment by jomi2801** [comment]
I very much appreciate that! Thanks for your fast reply and helpful explanations.
