### ISSUE TITLE
Trust-Region code does not handle a hard case

### ISSUE THREAD

**Issue by jomi2801** [felixlen/trlib#6]
It seems like the code has issues with a hard case problem. Here some code:
```
julia> using trlib
julia> g = [1.0, 0.0, -1.0]; H = zeros(3, 3); H[2, 2] = -20.0;
julia> tr = trlib.trlib_data(H, g);
julia> trlib.trlib_solve(tr, 1.0)
2
julia> tr.lam
1.4142135623730951
```
However the value `tr.lam` does not result in `H+lambda eye(3)` being positive definite. Hence, the tuple `(tr.sol, tr.lam)` cannot be an optimal solution of the trust-region problem, right?
Primal and dual feasibility as well as complementarity do hold since
```
julia> norm(tr.sol)
0.9999999999999999
julia> (H+tr.lam*eye(3))*tr.sol+g
3-element Array{Float64,1}:
 0.0
 0.0
 0.0
```
I would very much be interested in an explanation of this effect. Thanks!

**Comment by felixlen** [comment]
For your choice of `g` and `H` it holds `Hg = 0`, such that the Krylov subspace defined by `H` and `g` is the span of `g`, is `H`-invariant and not directly R^3. The method searches for a solution in the first invariant Krylov subspace encountered (that is almost always R^n), which is then a local solution (thus primal and dual feasibility hold, but no second order sufficient condition).

It is possible to extend the search to further Krylov subspaces and is also implemented in the C interface, if the user provides another `M`-orthogonal starting vector, but not implemented in the Julia interface.

**Comment by jomi2801** [comment]
Thank you very much for your explanation!

On Feb 24, 2018, at 6:25 AM, Felix Lenders <notifications@github.com<mailto:notifications@github.com>> wrote:


For your choice of g and H it holds Hg = 0, such that the Krylov subspace defined by H and g is the span of g, is H-invariant and not directly R^3. The method searches for a solution in the first invariant Krylov subspace encountered (that is almost always R^n), which is then a local solution (thus primal and dual feasibility hold, but no second order sufficient condition).

It is possible to extend the search to further Krylov subspaces and is also implemented in the C interface, if the user provides another M-orthogonal starting vector, but not implemented in the Julia interface.
