### ISSUE TITLE
python interface, pass matrix to Minv results in error

### ISSUE THREAD

**Issue by sjvrensburg** [felixlen/trlib#7]
According to the documentation, `trlib_solve` accepts an argument `invM` which may be a dense matrix. But passing a numpy array results in an error.

Minimal working example:
```python
import numpy as np
from trlib import trlib_solve

H = np.diag(np.arange(3)+1)
Minv = np.diag(1/np.sqrt(np.arange(3)+1))
g = np.array([-0.1, 0.2, 0.1])

trlib_solve(H, g, 1)                     # works
trlib_solve(H, g, 1, invM=Minv)  # produces error
```
The exact error read:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-c02cfcb4fd2d> in <module>()
----> 1 trlib_solve(H, g, 1, invM=Minv)

trlib.pyx in trlib.trlib_solve (/home/name/Documents/phd/models/lib/trlib/build/bindings/python/_trlib3.c:8832
)()

TypeError: 'numpy.ndarray' object is not callable
```

What am I doing wrong here? If I have to supply a function, how would I create one that preconditions based on the values of `H`, without recalculating the `H`.

**Comment by felixlen** [comment]
if you have a callable that computes the matrix vector product, it works with the current interface:
```trlib_solve(H, g, 1, invM=lambda d: Minv.dot(d))```
 However, the interface should be updated to also work with directly passing a matrix.

Best,
Felix

**Comment by sjvrensburg** [comment]
Thank you, using a callable works.
